### ISSUE TITLE
StopIteration: 'Image' object is not subscriptable

### ISSUE THREAD

**Issue by 437432655** [GeorgeSeif/Transfer-Learning-Suite#6]
When I make my own dataset , and try to run main.py , there is an error.

I created structure as :
-'dataset'
  -train
     -class1
         (include images)
     -class2
  -val
     -class1
     -class2

Details of the error followed:
Found 705 images belonging to 2 classes.
Found 361 images belonging to 2 classes.
Epoch 1/100
Traceback (most recent call last):
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/preprocessing/image.py", line 825, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/preprocessing/image.py", line 1233, in _get_batches_of_transformed_samples
    img = self.image_data_generator.preprocessing_function(img)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/applications/imagenet_utils.py", line 178, in preprocess_input
    mode=mode)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/applications/imagenet_utils.py", line 132, in _preprocess_symbolic_input
    x = x[..., ::-1]
TypeError: 'Image' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/he/pycharm/pycharm-2017.3.4/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/he/pycharm/pycharm-2017.3.4/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/he/pycharm/pycharm-2017.3.4/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/he/pycharm/pycharm-2017.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/he/Code/Transfer-Learning-Suite/main.py", line 206, in <module>
    validation_data=validation_generator, validation_steps=num_val_images // BATCH_SIZE, class_weight='auto', shuffle=True, callbacks=callbacks_list)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/he/anaconda2/envs/Yolo-keras/lib/python3.5/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: 'Image' object is not subscriptable

Thank you so much.

**Comment by 437432655** [comment]
I use ubuntu14.04  keras 2.1.5  tensorflow 1.4.0

**Comment by 437432655** [comment]
Fixed after change keras version to 2.1.4
